### ISSUE TITLE
Incorrect Information 🤦

### ISSUE THREAD

**Issue by colincowie** [jonathandata1/Pegasus-CatalanGate-False-Positives#1]
It took 5 seconds to search domain records and determine that `123tramites.com` has a Last Updated Date: 2022-05-21T19:04:14.000Z

Looking at the screenshot in your repository, it clearly states that 123tramites.com was a indictor from April 25th.

**Comment by jonathandata1** [comment]
![image](https://user-images.githubusercontent.com/106925/170633408-8ab2263e-2e06-4373-9210-f4ba756f3c55.png)

**Comment by jonathandata1** [comment]
I own 123tramites.com lol

**Comment by jonathandata1** [comment]
Closing this issue due to horrible OSINT skills,and a salty take from an amateur.
